#springBoot 启动端口
server:
  port: 8086
#dubbo
dubbo:
 application:
   name: dubbo-consumer  #dubbo的注册的服务名, 唯一性
 registry:
   address: zookeeper://49.232.11.224:2181  #注册zookeeper的地址
 protocol:
   name: dubbo
   port: 20880
 co

