#springBoot 启动端口
server:
  port: 8081
#rabbitMq
spring:
  rabbitmq:
    host: 49.232.11.224 #腾讯云服务器 rabbitMq 服务器IP
    port: 5672
    username: guest
    password: guest
    #redis
  redis:
    host: 49.232.11.224
#    host: 127.0.0.1
    port: 6379
#    timeout: 3



